### ISSUE TITLE
Improve release checklist

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/obol-docs#214]
# 🎯 Problem to be solved
We should improve the current release checklist (to fix ahead of tagging the release) according to the comments shared in https://docs.google.com/document/d/1Ku4IQ8EbMNcCVSi4awN6qcJOEs1rl-oV11Ygm1a0iis/edit#

# 🛠️ Proposed solution
- [ ]  The security.md page doesn't make a lot of sense and I would probably take some content out of it, not sure where the originally text came from (Section relating to biggest risk being who puts up the funds in particular)
- [ ]   It would be great if the `run a cluster` alone guide made sense with the CDVN repo. Thomas took a first stab at it, and I think it needs the folder structure fix as another iteration, but it still probably makes no sense, and needs fixing if not now then in v0.17.
- [ ] I would rather not instruct people they have to incur downtime to upgrade, it really reduces the usefulness of DVT. We should test that we can rotate one at a time and that we can rotate all at once and that neither risk slashing. Downtime based upgrades should happen next to never, definitely not for something like this such as changing a VC.
- [ ] Need to make better reference to the CDVN slashing risk, which is not currently present. Tag me when it's ready for re-review.

**Comment by OisinKyne** [comment]
Only the first two of these are applicable to this repo :)
